177 home domain
stellar-deprecated/transfer-server-validator pull request #178
Opened 2020-09-23 01:00 UTC by Zagan202

# Description

Check if the issuer account has the following
- "home_domain" key value
- "home_domain"'s value is the same as the given domain where the stellar.toml will be searched for at the following location:
`https://DOMAIN/.well-known/stellar.toml`

Note: 
I've added these tests to each SEP group test's `info.test.js` mostly because it seemed the most appropriate.

Addresses issue: (177)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [X] `npm run start:dev`
  - [X] Run SEP-6
  - [X] Run SEP-24
  - [X] Run SEP-31
  - [ ] Run optional tests
  - [X] DOMAIN testanchor.stellar.org
  - [X] Run on mainnet
- [X] `DOMAIN=https://testanchor.stellar.org npx jest -i info`
- [X] vscode debugger

2020-09-25 16:00 UTC, JakeUrban requested changes
Looks really good! I can tell you took the time to see how the SDK is used and how to expect stuff. LMK if you have questions about the syntax or `async/await` stuff. 

I do have requested changes though, I think mostly due to a misunderstanding about the scope of a single test run. A test run has a few parameters that the user can provide in the UI or CLI:
- mainnet `true/false`
- protocol `sep6/sep24/sep31`
- currency `SRT/USD/etc.`
- domain `testanchor.stellar.org, etc.`
- runOptionalTests `true/false`

These are the inputs we use to determine what we test on the anchor's service during this particular test run. If the anchor wants to test multiple currencies, they do multiple test runs.

2020-09-25 16:00 UTC, JakeUrban commented on cases-SEP24/toml.test.js
> +        for (const currency of toml.CURRENCIES) {
Ok so this is actually doing more than you need to do. Remember we have `process.env.CURRENCY` and `getActiveCurrency`, so when this code is run, it is only for _one currency, one issuer_.

Instead, remove the `for` loop and keep the contents. `currency` should be `process.env.CURRENCY` unless it is `null`/`undefined`, in which case you should use `getActiveCurrency`.

To break it down,
- `getActiveCurrency`
    - returns `{ enabledCurrency, infoJSON, currencies }`
    - `enabledCurrency` is the first enabled currency listed in their TOML. `currencies` are all enabled currencies. `infoJSON` as you'd probably guess is the `/info` response body.

2020-09-25 16:00 UTC, JakeUrban commented on cases-SEP24/toml.test.js
> +        for (const currency of toml.CURRENCIES) {
Also, don't wrap the whole function in a `try`. Only `try` things you know could fail, and specifically you know what they'd fail with so you can output a good error message.

The `expect` statement for example has no reason to be in the try block. What exception would be raised as a result of that line?

2020-09-25 16:00 UTC, JakeUrban commented on cases-SEP24/toml.test.js
> +        for (const currency of toml.CURRENCIES) {
This goes for the rest of the tests ^

2020-09-25 16:00 UTC, JakeUrban commented on cases-SEP31/toml.test.js
> +
SEP-31 `getActiveCurrency` is slightly different than the SEP-6 and 24 `getActiveCurrency`, but it returns the same type. Check out the source differences between the two and understand how they're walking through the anchor's information.

2020-09-26 06:21 UTC, Zagan202 commented
@JakeUrban I think I resolved all of your suggestions.

2020-09-28 16:25 UTC, JakeUrban reviewed
A few final changes but they should be simple. After that looks good!

2020-09-28 16:25 UTC, JakeUrban commented on cases-SEP24/toml.test.js
> +      for (const currency of toml.CURRENCIES) {
This great! But I think this test will pass if `enabledCurrency` is not in `toml.CURRENCIES`, which is possible if `enabledCurrency` comes from `process.env.CURRENCY`.

I would break the for loop when you find a match but put the `expect` statement outside the loop so it's always run.

2020-09-28 16:25 UTC, JakeUrban commented on cases-SEP31/toml.test.js
> +        enabledCurrency = process.env.CURRENCY;
Why not use `testCurrency`?

2020-09-28 17:41 UTC, Zagan202 commented on cases-SEP24/toml.test.js
> +      for (const currency of toml.CURRENCIES) {
Good catch!
I'm changing the logic such that if `enabledCurrency` is not in `toml.CURRENCIES` we fail with a much more appropriate message `"Cannot find an issuer of the enabled currency."`
At that point if the test passes this check we'll load the account and then run the `home_domain` expect check (outside the loop).

2020-09-28 17:49 UTC, JakeUrban commented on cases-SEP24/toml.test.js
> +      for (const currency of toml.CURRENCIES) {
that check for the passed currency should probably happen it it's own test. Can you add it? That way we can assume it's true for this test.

2020-09-28 17:49 UTC, JakeUrban commented on cases-SEP24/toml.test.js
> +      for (const currency of toml.CURRENCIES) {
or we should just fail with from a single test with two possible error states, but thats not ideal.

2020-09-28 18:01 UTC, JakeUrban approved these changes

2020-09-28 19:23 UTC, Zagan202 commented on cases-SEP24/toml.test.js
> +      for (const currency of toml.CURRENCIES) {
I'll refactor these in another branch and PR in a way where each expect is in its own test.
I have a way I want it done but its slightly out of scope for this task.

2020-09-28 19:26 UTC, merged